### ISSUE TITLE
Plug-in doesn't load in Cura 3.5.1

### ISSUE THREAD

**Issue by Ghostkeeper** [fieldOfView/Cura-SettingVisibilityProfileCreator#3]
Perhaps you know about this already, but just in case. This plug-in fails to load in Cura 3.5.1. In the log it puts the following error while loading plug-ins:

```
2019-11-08 16:40:18,661 - ERROR - [MainThread] UM.Logger.logException [84]: Exception: Import error loading module SettingVisibilityProfileCreator
2019-11-08 16:40:18,666 - ERROR - [MainThread] UM.Logger.logException [88]: Traceback (most recent call last):
2019-11-08 16:40:18,669 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/3.5/build/inst/lib/python3.5/site-packages/UM/PluginRegistry.py", line 546, in _findPlugin
2019-11-08 16:40:18,673 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/env/3.5/inst/lib/python3.5/imp.py", line 244, in load_module
2019-11-08 16:40:18,677 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/env/3.5/inst/lib/python3.5/imp.py", line 216, in load_package
2019-11-08 16:40:18,681 - ERROR - [MainThread] UM.Logger.logException [88]:   File "<frozen importlib._bootstrap>", line 693, in _load
2019-11-08 16:40:18,684 - ERROR - [MainThread] UM.Logger.logException [88]:   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
2019-11-08 16:40:18,687 - ERROR - [MainThread] UM.Logger.logException [88]:   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
2019-11-08 16:40:18,690 - ERROR - [MainThread] UM.Logger.logException [88]:   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
2019-11-08 16:40:18,694 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/home/cherubim/.local/share/cura/3.5/plugins/SettingVisibilityProfileCreator/SettingVisibilityProfileCreator/__init__.py", line 4, in <module>
2019-11-08 16:40:18,698 - ERROR - [MainThread] UM.Logger.logException [88]:     from . import SettingVisibilityProfileCreator
2019-11-08 16:40:18,702 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/home/cherubim/.local/share/cura/3.5/plugins/SettingVisibilityProfileCreator/SettingVisibilityProfileCreator/SettingVisibilityProfileCreator.py", line 21, in <module>
2019-11-08 16:40:18,706 - ERROR - [MainThread] UM.Logger.logException [88]:     from cura.Settings.SettingVisibilityPreset import SettingVisibilityPreset
2019-11-08 16:40:18,709 - ERROR - [MainThread] UM.Logger.logException [88]: ImportError: No module named 'cura.Settings.SettingVisibilityPreset'
2019-11-08 16:40:18,715 - WARNING - [MainThread] UM.PluginRegistry._populateMetaData [586]: Could not find plugin SettingVisibilityProfileCreator
2019-11-08 16:40:18,721 - ERROR - [MainThread] UM.Logger.logException [84]: Exception: Import error loading module SettingVisibilityProfileCreator
2019-11-08 16:40:18,725 - ERROR - [MainThread] UM.Logger.logException [88]: Traceback (most recent call last):
2019-11-08 16:40:18,729 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/3.5/build/inst/lib/python3.5/site-packages/UM/PluginRegistry.py", line 546, in _findPlugin
2019-11-08 16:40:18,733 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/env/3.5/inst/lib/python3.5/imp.py", line 244, in load_module
2019-11-08 16:40:18,736 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/build/env/3.5/inst/lib/python3.5/imp.py", line 216, in load_package
2019-11-08 16:40:18,740 - ERROR - [MainThread] UM.Logger.logException [88]:   File "<frozen importlib._bootstrap>", line 693, in _load
2019-11-08 16:40:18,744 - ERROR - [MainThread] UM.Logger.logException [88]:   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
2019-11-08 16:40:18,746 - ERROR - [MainThread] UM.Logger.logException [88]:   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
2019-11-08 16:40:18,749 - ERROR - [MainThread] UM.Logger.logException [88]:   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
2019-11-08 16:40:18,753 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/home/cherubim/.local/share/cura/3.5/plugins/SettingVisibilityProfileCreator/SettingVisibilityProfileCreator/__init__.py", line 4, in <module>
2019-11-08 16:40:18,756 - ERROR - [MainThread] UM.Logger.logException [88]:     from . import SettingVisibilityProfileCreator
2019-11-08 16:40:18,759 - ERROR - [MainThread] UM.Logger.logException [88]:   File "/home/cherubim/.local/share/cura/3.5/plugins/SettingVisibilityProfileCreator/SettingVisibilityProfileCreator/SettingVisibilityProfileCreator.py", line 21, in <module>
2019-11-08 16:40:18,763 - ERROR - [MainThread] UM.Logger.logException [88]:     from cura.Settings.SettingVisibilityPreset import SettingVisibilityPreset
2019-11-08 16:40:18,767 - ERROR - [MainThread] UM.Logger.logException [88]: ImportError: No module named 'cura.Settings.SettingVisibilityPreset'
```

It seems to be using a class which was newly introduced in Cura 3.6. In 3.6+ it works fine.

**Comment by fieldOfView** [comment]
Thanks for catching this. For the sake of keeping logs readable, I made a check for the import here: https://github.com/fieldOfView/Cura-SettingVisibilityProfileCreator/commit/0c992b6d0578de1c6b470ec8eccbce5d1fda089b
